### ISSUE TITLE
Error when trying to use can-define-backup with CanJS 4

### ISSUE THREAD

**Issue by rob4acre** [canjs/can-define-backup#10]
I get the following error message when trying to use can-define-backup with CanJS 4

The current version in npm is 0.0.1. I was getting an error about an incompatibility

`Error: You can't have two versions of can-dom-data-state, check your dependencies
`
I only get this error if I import can-define-backup

Thanks in advance for taking a look.

**Comment by phillipskevin** [comment]
`can-define-backup@1.0.0-pre.1` is compatible with CanJS 4.0. This can be installed with

```
npm install can-define-backup@pre
```

We may still include https://github.com/canjs/can-define-backup/issues/8 before making a final 1.0 version of `can-define-backup`, so there may be breaking changes if anyone starts using the pre-release.

I'm going to try to update the PR for the mixin proposal now to see if it is relatively easy to get in. If it is, I will release it soon.
