### ISSUE TITLE
Can't we Replace this with myMap.get()?

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/can-define-backup#16]
I am wondering as we want to backup the serialized state of the define map that we can get via myMap.get() and save and restore that to and from a var wouldn't that be the better method?

The idea behind this question is to use the nativ defineMap methods for set and get as this would be less magical 

```js
myMap = defineMap.extend()
myBackup = myMap,get()
myMap = defineMap.extend(myBackup) //Restore example is only for demonstration maybe set() is better :)

**Comment by chasenlehara** [comment]
You can do that if you want. This package also provides [isDirty](https://canjs.com/doc/can-define-backup.isDirty.html) and makes it so you don’t have to juggle multiple before/after values.
