### ISSUE TITLE
Proposal: align the interface with can-define-validate-validatejs.js

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define-backup#8]
@frank-dspeed commented on [Tue Feb 13 2018](https://github.com/canjs/can-map-backup/issues/48)

In
- https://github.com/canjs/can-define-validate-validatejs/blob/master/can-define-validate-validatejs.js

you can use 
```js
var defineValidate = require('can-define-validate-validatejs');
var User = DefineMap.extend({
    name: {
        validate: {
            presence: true
        }
    }
});
// Attach methods to any instance created of `User`
defineValidate(User);
```

my proposal is to do the same for can-map-backup or can-define-backup which is even a better name

```js
var defineBackup = require('can-define-backup'); // or can-map-backup
var User = DefineMap.extend({
    name: {
        validate: {
            presence: true
        }
    }
});
// Attach methods to any instance created of `User`
defineBackup(User);
```

---

@justinbmeyer commented on [Tue Feb 13 2018](https://github.com/canjs/can-map-backup/issues/48#issuecomment-365353849)

This would be great

**Comment by frank-dspeed** [comment]
@christopherjbaker please review #9
